// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC03uAmGhIkisa3U6Xc-FvkZa6p7xdZf9U',
    appId: '1:474590834730:web:bd92956eb64f26117d9353',
    messagingSenderId: '474590834730',
    projectId: 'modernisum-fe2ce',
    authDomain: 'modernisum-fe2ce.firebaseapp.com',
    storageBucket: 'modernisum-fe2ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKJxjwZiz2ST_7Ic-xVtIzfc4lj9YNiqw',
    appId: '1:474590834730:android:6770c5ab2be84c527d9353',
    messagingSenderId: '474590834730',
    projectId: 'modernisum-fe2ce',
    storageBucket: 'modernisum-fe2ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbeGWYlxouo5PuPTpldnPwYppps9aBwSo',
    appId: '1:474590834730:ios:169008969f8d15457d9353',
    messagingSenderId: '474590834730',
    projectId: 'modernisum-fe2ce',
    storageBucket: 'modernisum-fe2ce.firebasestorage.app',
    iosBundleId: 'com.example.flutterPortfolio',
  );
}
